server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    username: binhtien
    password: tien123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/.well-known/jwks.json

#jwt:
#  private-key: classpath:keys/private.pem
#  public-key: classpath:keys/public.pem
#  access-token-expiration: 3600000  # 1 hour in milliseconds
#  refresh-token-expiration: 86400000  # 24 hours in milliseconds

security:
  jwt:
    signer-key: "FmA-URKHIPBuDhcdCHB?nkJk?ckjc2ksiVLONEwt5rV9/gS96iZBUEybn2mgw3CC"
    valid-duration: 3600  # 1h
    refresh-duration: 360000  # 100h
logging:
  level:
    org:
      springframework: INFO
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql: TRACE  # Hiển thị giá trị tham số trong SQL queries
    com.example.projectmanager: DEBUG  # Log cho package của dự án